### ISSUE TITLE
Arrow should point down when cooling

### ISSUE THREAD

**Issue by murphy2712** [imrahil/OctoPrint-NavbarTemp#11]
Currently there's only one arrow icon pointing up, which is good to show when the temperature is increasing.

However when temperature is above what's required, the arrow should point down.

![screenshot 2015-09-09 17 02 37](https://cloud.githubusercontent.com/assets/712327/9765478/a6e569bc-5714-11e5-9954-658c523b1322.png)

**Comment by imrahil** [comment]
Fixed in version 0.8
