### ISSUE TITLE
Plugin forgets RasPi temp being disabled

### ISSUE THREAD

**Issue by jangrewe** [imrahil/OctoPrint-NavbarTemp#14]
When i open the settings, disable the RasPi temp display and save it, the RasPi temp is hidden.
If i now open the settings again, change something else and save again, the RasPi temp is displayed again, even though i didn't enable it again.

OctoPrint 1.2.16 and 1.2.17, everything updated.

**Comment by imrahil** [comment]
sorry. can't replicate. Could you try with Octoprint 1.3 ?
