### ISSUE TITLE
Enhancement Please - Raspi CPU %

### ISSUE THREAD

**Issue by Eddiiie** [imrahil/OctoPrint-NavbarTemp#16]
Hello,
Love your plug in.   Is there any chance you could add one more item to it and that would be the current CPU usage of the Raspi?

I often wonder what the under-lying CPU usage is.

Thank you for your consideration.

**Comment by imrahil** [comment]
[lazy-mode] what's the command to check CPU usage? [/lazy-mode] :)

**Comment by Eddiiie** [comment]
Hi,


I found and tested a script on Octoprint / Raspberry Pi.





Taken from this URL:  http://askubuntu.com/questions/450045/get-cpu-usage-in-command


It seems to work well.


Thank you for your consideration!


[https://cdn.sstatic.net/Sites/askubuntu/img/apple-touch-icon@2.png?v=c492c9229955]<http://askubuntu.com/questions/450045/get-cpu-usage-in-command>

server - get cpu usage in command - Ask Ubuntu<http://askubuntu.com/questions/450045/get-cpu-usage-in-command>
askubuntu.com
To get cpu usage, best way is to read /proc/stat file. See man 5 proc for more help. There is a useful script written by Paul Colby i found here








Text:

To get cpu usage, best way is to read /proc/stat file. See man 5 proc for more help.

There is a useful script written by Paul Colby i found here<http://www.mail-archive.com/linuxkernelnewbies@googlegroups.com/msg01690.html>

#!/bin/bash
# by Paul Colby (http://colby.id.au), no rights reserved ;)

PREV_TOTAL=0
PREV_IDLE=0

while true; do

  CPU=(`cat /proc/stat | grep '^cpu '`) # Get the total CPU statistics.
  unset CPU[0]                          # Discard the "cpu" prefix.
  IDLE=${CPU[4]}                        # Get the idle CPU time.

  # Calculate the total CPU time.
  TOTAL=0

  for VALUE in "${CPU[@]:0:4}"; do
    let "TOTAL=$TOTAL+$VALUE"
  done

  # Calculate the CPU usage since we last checked.
  let "DIFF_IDLE=$IDLE-$PREV_IDLE"
  let "DIFF_TOTAL=$TOTAL-$PREV_TOTAL"
  let "DIFF_USAGE=(1000*($DIFF_TOTAL-$DIFF_IDLE)/$DIFF_TOTAL+5)/10"
  echo -en "\rCPU: $DIFF_USAGE%  \b\b"

  # Remember the total and idle CPU times for the next check.
  PREV_TOTAL="$TOTAL"
  PREV_IDLE="$IDLE"

  # Wait before checking again.
  sleep 1
done


save it to cpu_usage, add execute permission chmod +x cpu_usage and run:

./cpu_usage


to stop the script, hit Ctrl+c

share<http://askubuntu.com/a/450136>improve this answer<http://askubuntu.com/posts/450136/edit>






________________________________

**Comment by Swiftnesses** [comment]
This would be an awesome feature!

**Comment by mtmello2003** [comment]
Agree.! could be great feature.

**Comment by Cosik** [comment]
@Eddiiie @Swiftnesses @mtmello2003 what do you think if we will give you possibility to execute custom command in shell and print results on Navbar?

**Comment by mtmello2003** [comment]
For sure will be the best option: let the user custom by them self.

**Comment by Eddiiie** [comment]
@Cosik That would be pretty cool and include the above script as a default?

**Comment by Cosik** [comment]
@Eddiiie I'm not sure if in first releases there will be something like "default"

**Comment by Cosik** [comment]
@Eddiiie Hi we prepared new feature for custom commands, please read this https://github.com/imrahil/OctoPrint-NavbarTemp/pull/52

**Comment by Cosik** [comment]
This could be done by custom command.
