### ISSUE TITLE
Feature request - Show temperature of Orange Pi

### ISSUE THREAD

**Issue by nppc** [imrahil/OctoPrint-NavbarTemp#20]
Is this possible to show temperature of Orange Pi board, not only RaspPi?
Command, showing H3 temperature is this: cat /sys/devices/virtual/thermal/thermal_zone0/temp
Thanks!

**Comment by nppc** [comment]
Ah, nice! There is already a pull Request for similar thing.

**Comment by mef78** [comment]
+1 for showing temp of Orange Pi board.

**Comment by Cosik** [comment]
Hi, please watch this PR https://github.com/imrahil/OctoPrint-NavbarTemp/pull/38

**Comment by rafalmag** [comment]
This issue can be closed - it shows the temperature for OrangePi Pc Plus very well.
