### ISSUE TITLE
[Enhancments] Other stats for rpi.

### ISSUE THREAD

**Issue by ghost** [imrahil/OctoPrint-NavbarTemp#24]
It would be cool to see like a dropdown button or something that shows more stats about the raspberry pi like free ram, cpu usuage and so on :)

**Comment by Cosik** [comment]
@eXqusic please look here https://github.com/imrahil/OctoPrint-NavbarTemp/issues/16 will it be ok for you?

**Comment by Cosik** [comment]
@eXqusic  Hi we prepared new feature for custom commands, please read this https://github.com/imrahil/OctoPrint-NavbarTemp/pull/52
