### ISSUE TITLE
Themeify + NavbarTemp - text not visable 

### ISSUE THREAD

**Issue by dragonnn** [imrahil/OctoPrint-NavbarTemp#26]
They is a nice plugin called Themeify with allows you to customize look of Octoprint. Nice black theme called Discorded.  Unfortunately it doesn't work good with NavbarTemp - text has the same color as navbar color is. 
I tried add an option in it to change . navbar-text color but this only changes color of Bed temp, Tool stays at the old color.

**Comment by mstofflett** [comment]
Is there a fix for this?

**Comment by Peboli** [comment]
Yes there is a workaround.
In the Themeify setup page, click on 'Advanced options' text to unfold advanced settings, under 'Custom style' click  on the [NEW] button and fill it like this
![image](https://user-images.githubusercontent.com/16508054/45263831-8efad300-b431-11e8-9ada-5833ddec06bb.png)
Then click on [SAVE]

**Comment by Nuttavoot** [comment]
> Yes there is a workaround.
> In the Themeify setup page, click on 'Advanced options' text to unfold advanced settings, under 'Custom style' click on the [NEW] button and fill it like this
> ![image](https://user-images.githubusercontent.com/16508054/45263831-8efad300-b431-11e8-9ada-5833ddec06bb.png)
> Then click on [SAVE]

This works only the first time after clicked setting again it disappeared only Bed temp stayed visible.

**Comment by eddiePower** [comment]
I found i needed to use the following setting to uncover the text covered up.

<img width="834" alt="Screen Shot 2021-01-02 at 1 09 08 am" src="https://user-images.githubusercontent.com/431783/103440131-3fdaab00-4c97-11eb-98bb-395bdfe65c2a.png">

Selector: .socInfo
CSS-Rule: padding
Color Picker: leave as is
Value: 60, 10

that gives the area around the onboard SOC temp for me the chars "Pi: 50.6C" if you need more room add to the first value 60. and reduce that value if you need less space.

Hope it helps even tho its a very old issue, ive only just come accross it.

**Comment by LazeMSS** [comment]
Fixed in latest release

**Comment by LazeMSS** [comment]
Its already included https://github.com/imrahil/OctoPrint-NavbarTemp/pull/84

This issue could be closed.
