### ISSUE TITLE
[Enhancments] Add Fan Speed

### ISSUE THREAD

**Issue by GingerNutt** [imrahil/OctoPrint-NavbarTemp#31]
The title says it all, could you add the fan speed please?

Yours Roy

**Comment by Cosik** [comment]
@GingerNutt could it be as an option in config? @imrahil What do you think about it?

**Comment by imrahil** [comment]
How it could be possible? Is there any readings with fan speed?

**Comment by ntoff** [comment]
https://github.com/ntoff/OctoPrint-FanSpeed

Fan speed is read from gcode sent *to* the printer, and also responses *from* the printer, if it's running repetier firmware. I don't know about marlin or klipper or teacup as I don't run those firmwares.

**Comment by Cosik** [comment]
I don't have repetier firmware to test it. Maybe we will think in the future what to do with it.
