### ISSUE TITLE
NavbarTemp vs Room Temp

### ISSUE THREAD

**Issue by louw9669** [imrahil/OctoPrint-NavbarTemp#32]
I thought these were 2 separate plug ins but when I installed the NavBar the Room would not show up in plugin area. then I thought I read that the room temp was part of the navbar but I don't see it there. I really would like all the temps on the bar. am I missing something or it just wont work that way

thanks

**Comment by Cosik** [comment]
Hi, 
@louw9669 how room temp should be read? I'm thinking about adding 1-wire sensors support to this plugin.

**Comment by Cosik** [comment]
@louw9669 Hi we prepared new feature for custom commands, please read this https://github.com/imrahil/OctoPrint-NavbarTemp/pull/52
