### ISSUE TITLE
Settings view is missing - #settings_plugin_navbartemp does not exist

### ISSUE THREAD

**Issue by martinj** [imrahil/OctoPrint-NavbarTemp#33]
The following output can be seen in the console.

> Did not bind view model NavbarTempViewModel to target #settings_plugin_navbartemp since it does not exist

Octoprint version 1.3.6

**Comment by martinj** [comment]
Wasn't connected to the printer. Doh!
Once I connected it showed up, though it doesn't seem to register the rapsberry temp, might be due to being the latest raspberry 3 B+

**Comment by imrahil** [comment]
I think it's because 3 B+ has new processor ID

**Comment by martinj** [comment]
Actually I copied and paste the code for the detection, the hardware still matches.
I was mixing things up. It still exists a problem, its the settings view thats not show and i can't enable show raspberry temp.

**Comment by Yury-MonZon** [comment]
Same here =( I see the hotend temp in the navbar, but couldn't find the settings.

**Comment by Cosik** [comment]
@martinj could we close this issue or some action are needed?
