### ISSUE TITLE
NavbarTemp + Themeify = Can't see text

### ISSUE THREAD

**Issue by OutsourcedGuru** [imrahil/OctoPrint-NavbarTemp#35]
If you have `Themeify` also loaded and it's using the default color scheme, it appears that the text doesn't display for your plugin.

There is a work-around by adding a custom CSS style in Themeify itself:

```
Selector:  .navbar-text
CSS-Rule:  color
Value:     #ffffff
```

**Comment by Nuttavoot** [comment]
> If you have `Themeify` also loaded and it's using the default color scheme, it appears that the text doesn't display for your plugin.
> 
> There is a work-around by adding a custom CSS style in Themeify itself:
> 
> ```
> Selector:  .navbar-text
> CSS-Rule:  color
> Value:     #ffffff
> ```

After click on Octoprint setting again, the Tool temp disappeared again.

**Comment by Cosik** [comment]
@Nuttavoot @OutsourcedGuru  this is related to #64. Please pass there information how to fix it if you know how.
