### ISSUE TITLE
NavBar Temp settings to fahrenheit from celcius?

### ISSUE THREAD

**Issue by azz7686** [imrahil/OctoPrint-NavbarTemp#37]
I'm fairly new to all this, is there a command or option for fahrenheit readings instead of celcius? TYIA

**Comment by Cosik** [comment]
@azz7686 I think it will be hard, all values are taken direct from system/firmware. So additional thing should be checking based units.

**Comment by imrahil** [comment]
I think that we can add an option to "force" recalculate readings from system to Fahrenheit degrees (if system provides them in Fahrenheit and user selects recalculate option it will be incorrect obviously)

**Comment by LazeMSS** [comment]
Fixed in latest release

**Comment by LazeMSS** [comment]
Its already included https://github.com/imrahil/OctoPrint-NavbarTemp/pull/84

This issue could be closed.
