### ISSUE TITLE
FR: Ultimachine Einsy Temp

### ISSUE THREAD

**Issue by kickhad** [imrahil/OctoPrint-NavbarTemp#39]
Would be great if there was an option to get the Einsy Rambo temp on the Navbar. I keep my RPi outside the enclosure, the Einsy is in.

**Comment by Cosik** [comment]
@kickhad I see some problems:
1. Have no Einsy Rambo for testing
2. Have no idea how to get information about temperature.
3. There are PR which are not merged to master

**Comment by kickhad** [comment]
I'm not sure it is parsed into the OctoPrint datamodel.

**Comment by Cosik** [comment]
@kickhad is this feature still valid?

**Comment by arekm** [comment]
Duplicate of https://github.com/imrahil/OctoPrint-NavbarTemp/issues/87 (which is newer but has more info about obtaining einsy board temperature, so closing this one).
