### ISSUE TITLE
Heating indication

### ISSUE THREAD

**Issue by arekm** [imrahil/OctoPrint-NavbarTemp#4]
Would be nice if it was indicated that heating of hotend/bed is turned on, for example:
"Hotend: 48°C -> 210.3°C Bed: 20.3°C -> 50.3°C" (so current -> target temperature)

I saw that it sometimes shows "off" which makes no sense to me. I mean hotend and bed always have some temperature and such temperature should be shown IMO (regardless if heating is on or off). If printer is not connected then no point in showing anything at all.

Edit: Ok, it could be "Hotend: 25°C -> Off, Bed: 25°C -> Off" when off.

ps. KISS rule, so no option needed for it, make it default ;-)
ps2. instead of "->" maybe some unicode arrow like http://unicode-table.com/en/2B08/ or http://unicode-table.com/en/2197/

**Comment by eboston** [comment]
I had been planning on making the same request.  +1 to this.  Would be good to know if the heater is on or not.
