### ISSUE TITLE
temperature not updated when heating "manually"

### ISSUE THREAD

**Issue by arekm** [imrahil/OctoPrint-NavbarTemp#5]
Current temperature doesn't get updated if we tell octoprint to heat hotend (without actually printing). So Temperature -> Set , choose some profile like PLA for hotend. Hotend starts to heat up but temperature shown by navbartemp is not being updated.

**Comment by imrahil** [comment]
c'mon! that's the core functionality for this plugin! :) it works! I'm using it all the time!
do you have temperature readings below graph? if yes, there should be the same values on top nav  bar..

**Comment by arekm** [comment]
Hehe, works when print is in progress but not in other cases. Looks like OctoPrint problem since graphs and text values in Temperature tab are also not being updated :-/

Closing, will report to the proper place.
