### ISSUE TITLE
Printoid not see the temperature of the system

### ISSUE THREAD

**Issue by ShohninDmitriy** [imrahil/OctoPrint-NavbarTemp#51]
Printoid not see the temperature of the system after the upgrade to version 0.11

**Comment by Cosik** [comment]
Sad to hear but we don't have any connections with printoid. Please contact them or ask them to sync with us.

**Comment by Cosik** [comment]
@ShohninDmitriy problem is already fixed?

**Comment by ShohninDmitriy** [comment]
yes
