### ISSUE TITLE
Tool temperature 0.0°C when used with Room Temperature Plugin

### ISSUE THREAD

**Issue by FX117** [imrahil/OctoPrint-NavbarTemp#53]
The Tool temperature is 0.0°C when used together with Room Temperature Plugin (https://github.com/l00ma/OctoPrint-roomTemp).

After removing Room Temperature Plugin the tool temperature is displayed properly again.

I'm on OctoPrint version 1.3.9

Thanks

**Comment by Cosik** [comment]
Hmmm, @FX117 you rise issue for this plugin, because other one break working of it?

**Comment by FX117** [comment]
I'm sorry, what would be the proper procedure?
I've also raised an issue on the OctoPrint-roomTemp page

**Comment by Quas7** [comment]
at least FX117 highlighted this as I was just about to open an issue about that. :)
Will deactivate the other plugin now.
