### ISSUE TITLE
Not difficult to read - Change fonts

### ISSUE THREAD

**Issue by stonefox1958** [imrahil/OctoPrint-NavbarTemp#55]
Why is the text look like this. It's very defficult to read. Can I change fonts or ?

![navbar----2019-01-28_19-04-07](https://user-images.githubusercontent.com/8201781/51856404-eb528680-232f-11e9-95a9-c7846c82c711.jpg)

**Comment by Cosik** [comment]
@stonefox1958 this is duplicated by #64 if you are able please provide info in that issue.
