### ISSUE TITLE
[Feature Request] Make more room on the navbar

### ISSUE THREAD

**Issue by goscicki** [imrahil/OctoPrint-NavbarTemp#57]
The navbar is sometimes very crowded, so it would be nice to have an option to just show the actual temps instead of the actual and target temps. A toggle could allow users to choose.

**Comment by RafaelSchridi** [comment]
Yeah a setting would be nice [because I have too much stuff up there](https://i.imgur.com/wRVaXCJ.png) 😅

**Comment by Cosik** [comment]
@goscicki and @RafaelSchridi please provide some example or proposal of solution/

**Comment by RafaelSchridi** [comment]
This is what I was thinking:
https://i.imgur.com/djKxKKT.png
Hiding the target temperature (not sure what to do with the arrows though, maybe show a different icon if its close?)

**Comment by Cosik** [comment]
Hmmm, I will try to make this as optional thing.

**Comment by Cosik** [comment]
@RafaelSchridi some of steps has been done, please check #29 you could test it on latest devel branch.

**Comment by Cosik** [comment]
@RafaelSchridi I've made additional improvements. Please check if it's ok, or there is still room for improvement.

**Comment by forthereg** [comment]
I came here from google looking for this exact thing.
I just need to monitor the Rpi SOC temp as it sits in the heated chamber and this is the ONLY plugin that lets you display Pi temps .
If you could please add option to only display SOC temps, that would be fantastic. 
this is what my bar looks like, makes in into 3 rows  :
![nav temp ](https://user-images.githubusercontent.com/52065997/77728584-b8b82280-6ff4-11ea-9d21-c9856b511f8a.jpg)

**Comment by forthereg** [comment]
I came here from google looking for this exact thing.
I just need to monitor the Rpi SOC temp as it sits in the heated chamber and this is the ONLY plugin that lets you display Pi temps .
If you could please add option to only display SOC temps, that would be fantastic, Thank you.
this is what my bar looks like, makes it into 3 rows, :
![nav temp ](https://user-images.githubusercontent.com/52065997/77728978-89ee7c00-6ff5-11ea-88a1-6d76e76b7b7d.jpg)

**Comment by Cosik** [comment]
@forthereg first please check devel branch if it helps a little bit.

**Comment by RafaelSchridi** [comment]
@Cosik Sorry took to long, been a bit hectic lately. But everything looks great on the devel branch, this was exactly what i was looking for. 
Thanks for all the work man!

For the curious this is how it looks now with everything enabled:
![chrome_2020-03-31_15-58-12](https://user-images.githubusercontent.com/11460682/78034858-957cd280-7368-11ea-9ff9-9c103cf34b18.png)
