### ISSUE TITLE
[REQUEST] Add raspberry pi core temperature to graph display... or at least somewhere in the GUI

### ISSUE THREAD

**Issue by bolsoncerrado** [imrahil/OctoPrint-NavbarTemp#6]
:P

**Comment by imrahil** [comment]
Fixed in version 0.5

**Comment by bolsoncerrado** [comment]
Call me picky but... couldnt raspi temp appear even if you're not yet connected to the printer? :D in the end, octoprint already runs from the raspi even if there's no printer attached ;)

**Comment by imrahil** [comment]
Good point. I'll fix it!

**Comment by bolsoncerrado** [comment]
Thanks!! ;)

**Comment by imrahil** [comment]
Fixed in 0.6

**Comment by jminardi** [comment]
Would it be possible to configure whether or not the raspi temp is displayed?

**Comment by imrahil** [comment]
@jminardi at the moment it's not possible to turn it off :) but if it's annoying for you I can add switch in Settings dialog

**Comment by jminardi** [comment]
@imrahil A switch in the settings dialog would be awesome

**Comment by imrahil** [comment]
Added in version 0.7

**Comment by jminardi** [comment]
Awesome!
