### ISSUE TITLE
RPi 4 : No temps showing up

### ISSUE THREAD

**Issue by DeRocca** [imrahil/OctoPrint-NavbarTemp#61]

**Comment by DeRocca** [comment]
I have Octoprint on a RPi 4, and nothing is showing up. I have nothing connected (maybe normal ?)

**Comment by Cosik** [comment]
@DeRocca you need to connect to your 3D printer to get values on navbar. Please check it.

**Comment by rafalmag** [comment]
Might be connected to https://github.com/imrahil/OctoPrint-NavbarTemp/issues/65

**Comment by galosre** [comment]
Same issue for PI 3+ no temp.

**Comment by Cosik** [comment]
No more details provided. Issue closed.
