### ISSUE TITLE
Display Fahrenheit as well as Celsius

### ISSUE THREAD

**Issue by tvirelli** [imrahil/OctoPrint-NavbarTemp#63]
Can you make it so there is a checkbox to show temp in either  Fahrenheit, Celsius or both at the same time? Or better yet, just check if the "Show temperatures in Fahrenheit as well as Celsius" checkbox is checked under appearance? Thanks!

**Comment by Cosik** [comment]
This will required more work because way of getting temperature will required rewriting

**Comment by LazeMSS** [comment]
Fixed in latest

**Comment by 44knight44** [comment]
Just wondering if you can just use this formula (0°C × 9/5) + 32 = 32°F to convert it to Fahrenheit. Make the temperature a variable and just plug it in.

**Comment by LazeMSS** [comment]
Its already included https://github.com/imrahil/OctoPrint-NavbarTemp/pull/84

This issue could be closed.
