### ISSUE TITLE
Themeify compatible

### ISSUE THREAD

**Issue by pawaller** [imrahil/OctoPrint-NavbarTemp#64]
Is it possible to make your plugin compatible with the "themeify" plugin.
I.e it takes the font color etc from the applied theme.

Thanks

**Comment by buchnoun** [comment]
I would love that too !! it was working fine and stopped... very frustrating

**Comment by ChaosBlades** [comment]
Ah, so that is why it doesn't work.

**Comment by Cosik** [comment]
@pawaller @buchnoun @ChaosBlades are you able to pass information when last it was working with themeify?

**Comment by iMattmax** [comment]
![51856404-eb528680-232f-11e9-95a9-c7846c82c711](https://user-images.githubusercontent.com/9829798/83437604-52121380-a440-11ea-853b-e320ad4403fc.jpg)
I have the same result with using this (OctoPrint-NavbarTemp) and Themeify

**Comment by ChaosBlades** [comment]
I gave up on Themeify. I just use Dark Reader now  which is a browser plugin. Works perfectly and looks way better than the Themeify themes.

https://github.com/darkreader/darkreader

![Image of Dark Reader on OctoPrint](https://i.imgur.com/3D3ldLV.png)

**Comment by Cosik** [comment]
Sorry I don't have enough skills to fix this issue.

**Comment by iMattmax** [comment]
> I gave up on Themeify. I just use Dark Reader now which is a browser plugin. Works perfectly and looks way better than the Themeify themes.
> 
> https://github.com/darkreader/darkreader
> 
> ![Image of Dark Reader on OctoPrint](https://camo.githubusercontent.com/8d0632a6ecc1830ad1ed587a1660658a6d69f539/68747470733a2f2f692e696d6775722e636f6d2f3344336c644c562e706e67)

how did you change the order of the tasks (temperature, terminal, etc.)?

**Comment by ChaosBlades** [comment]
@iMattmax I think you are looking for the plug-in called 'Dragon Order'

https://github.com/jneilliii/OctoPrint-DragonOrder

**Comment by djalexz** [comment]
Hi, you can set the following Settings in Themeify Options:

![image](https://user-images.githubusercontent.com/11389551/89024319-308cb580-d325-11ea-87e4-83f7bc9b6082.png)

The Text in Navbar is now in the color of .navbar-text.

![image](https://user-images.githubusercontent.com/11389551/89024451-6893f880-d325-11ea-8aa7-deb17f7b244e.png)

**Comment by LazeMSS** [comment]
Fixed in latest release

**Comment by LazeMSS** [comment]
Its already included https://github.com/imrahil/OctoPrint-NavbarTemp/pull/84

This issue could be closed.
