### ISSUE TITLE
Custom command is not shown

### ISSUE THREAD

**Issue by BigDi** [imrahil/OctoPrint-NavbarTemp#69]
I tried the example uname put the navbar is not updated after restart of octoprint. The log file of octroprint won't show an error. What can be wrong?

**Comment by Cosik** [comment]
@BigDi did you wait enough time? Refresh time is about 30 second. If it will not help, please check latest devel. Currently I'm fixing some bugs.

**Comment by Cosik** [comment]
no response from @BigDi
