### ISSUE TITLE
Only CPU Temperature show ?

### ISSUE THREAD

**Issue by fredondem** [imrahil/OctoPrint-NavbarTemp#70]
Hello, is it possible to see in the Navbar the CPU temperature "Only" ?
Thank's.

**Comment by fredondem** [comment]
I just install "Devel Branch". It's best for me. 
The best would be to have the choice to display what we would like to see between the three temp.
Nice job.

**Comment by Fonkyup** [comment]
It work for me too with the Devel Branch
