### ISSUE TITLE
Raspi Temp not visible

### ISSUE THREAD

**Issue by arut16** [imrahil/OctoPrint-NavbarTemp#71]
Hi everyone !

Just installed my fresh new RPi 4 with last Octoprint and NavBarTemp Plugin. Working well for bed/tool temp but it not showing RPi Soc Temp. Why ?

![Capture](https://user-images.githubusercontent.com/58274805/81225320-584fd400-8fe9-11ea-9782-762d94f25d61.PNG)

**Comment by Cosik** [comment]
Have  no idea. You didn't provide any information. Why?

**Comment by arut16** [comment]
@Cosik witch information do you need ? Sorry I'm a beginner.

**Comment by Cosik** [comment]
Please enable full logging for plugin and attache to this issue. Also few minutes ago I release 0.14 version. Please check it first.

**Comment by arut16** [comment]
@Cosik I updated to 0.14 but SOC temp still not shown : 
![image](https://user-images.githubusercontent.com/58274805/81332340-3dda3100-90a3-11ea-8cb7-5e138da67332.png)
And for logs, which one do I need upload here ? 
![image](https://user-images.githubusercontent.com/58274805/81332557-8eea2500-90a3-11ea-955d-74abc96bda04.png)

**Comment by Cosik** [comment]
1. https://docs.octoprint.org/en/master/bundledplugins/logging.html
2. If something is not working you could use custom commands.
3. Please carefully read https://github.com/imrahil/OctoPrint-NavbarTemp/blob/master/README.md
4. I have no rpi4 to test it.

**Comment by arut16** [comment]
@Cosik Thanks for helping :
1 : I read it. Here logs : https://gist.github.com/arut16/d2f934afa5e332d664a8552556a7faf9
2  : What do you meen custom commands ? How ? Where ?
3 : Read it. Didn't help...
4 : Should be same as Pi3 at this point no?

**Comment by Cosik** [comment]
You answers didn't help. Log is still not correct. In readme you have information about custom commands and what to do when platform is not supported. I uploaded issue template. Please fill it.

**PLEASE CAREFULLY FILL EACH POINT**

**1. Hardware and operating system version:**


**2. Octoprint version:**


**3. Plugin version:**


**4. Print screen of plugin configuration:**


**5. Plugin full log file**


**6. Clear problem description::**


**7. Expectation:**

**Comment by arut16** [comment]
**1. Hardware and operating system version:**

Raspberry 4 2Go RAM version
Octopi v.0.17.0

**2. Octoprint version:** v1.4.0

**3. Plugin version:** 0.14

**4. Print screen of plugin configuration:** 
![image](https://user-images.githubusercontent.com/58274805/81415919-569d2200-9149-11ea-902f-99fb6932a1f5.png)

**5. Plugin full log file** : Don't know how to do that...

**6. Clear problem description:** RPi SOC Temp is not appears

**7. Expectation:** RPi SOC Temp Appears with tool and bed temp.

**Comment by arut16** [comment]
I find a solution with a custom command : 
![image](https://user-images.githubusercontent.com/58274805/81416781-7ed95080-914a-11ea-8799-8d3f9c4031e7.png)
![image](https://user-images.githubusercontent.com/58274805/81416813-8c8ed600-914a-11ea-860f-903354bb6315.png)

**Comment by Cosik** [comment]
@arut16 you could add to cmd
` | cut -d'=' -f2'`

**Comment by arut16** [comment]
@Cosik Like this : `/opt/vc/bin/vcgencmd measure_temp | cut -d'=' -f2'`

**Comment by arut16** [comment]
@Cosik This command work : `/opt/vc/bin/vcgencmd measure_temp | sed -e 's/temp=//'`
With `| cut -d'=' -f2'`, not working
![image](https://user-images.githubusercontent.com/58274805/81471203-cbc33280-91ef-11ea-9677-d2fc42548a0e.png)
![image](https://user-images.githubusercontent.com/58274805/81471209-d8e02180-91ef-11ea-9e6c-e4029fa7fee9.png)

**Comment by dan-and** [comment]
> cut -d'=' -f2'

It works, but there is just a missing single quote:
cut -d'=' -'f2'

so using:
/opt/vc/bin/vcgencmd measure_temp|cut -d'=' -'f2'
as a custom command helps. 

Please note that changes in the custom commands in the NavbarTemp plugin need a restart of octoprint!
