### ISSUE TITLE
No SoC temperature

### ISSUE THREAD

**Issue by tsndr** [imrahil/OctoPrint-NavbarTemp#74]
**PLEASE CAREFULLY FILL EACH POINT**

**1. Hardware and operating system version:**
<details>
<summary><code>/proc/cpuinfo</code></summary>

```
processor       : 0
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 108.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2711
Revision        : b03111
Serial          : 1000000053479ad8
Model           : Raspberry Pi 4 Model B Rev 1.1
```
</details>

<details>
<summary><code>/etc/debian_version</code></summary>

```
10.4
```
</details>

<details>
<summary><code>rpi-eeprom-update</code></summary>

```
BCM2711 detected
Dedicated VL805 EEPROM detected
BOOTLOADER: up-to-date
CURRENT: Thu 16 Apr 17:11:26 UTC 2020 (1587057086)
 LATEST: Thu 16 Apr 17:11:26 UTC 2020 (1587057086)
 FW DIR: /lib/firmware/raspberrypi/bootloader/critical
VL805: up-to-date
CURRENT: 000137ad
 LATEST: 000137ad
```
</details>

**2. Octoprint version:**
`1.4.0`

**3. Plugin version:**
`0.14`

**4. Print screen of plugin configuration:**
<details>
<summary>Screenshot</summary>

<img width="539" alt="Navbar_Temp_Settings" src="https://user-images.githubusercontent.com/2940127/83944731-ff50a700-a805-11ea-951a-1638f4097607.PNG">
</details>

**5. Plugin full log file**
There is no logfile.

**6. Clear problem description::**
If no printer is connected the Navbar shows `Tool: 0.0°C`, but it should show the SoC's temperature.
If a printer is connected it shows `Tool: 21.0°C Bed: 20.6°C` which is fine, but it's still missing the SoC's temperature.

**7. Expectation:**
If no printer is connected the output should be: `SoC: 52.0°C`.
If a printer is connected the output should be: `SoC: 52.0°C Tool: 21.0°C Bed: 20.6°C`

**Comment by Cosik** [comment]
@tsndr you need to enable logging. Also it looks like #71

**Comment by tsndr** [comment]
How do I do that?

**Comment by V0lk1s** [comment]
Could this be related to the problem I found with 64-bit version of Raspberry OS? The command for checking SoC temperature on a Raspberry have a different path.
I edited the sbc.py line 103 and replaced the path to 'usr/bin/vcgencmd' and then it worked.

**Comment by ManuelMcLure** [comment]
I ran into a similar problem when I upgraded my OctoPrint instance to use Python 3 instead of Python 2. I tracked it down to line 40 of ``__init.py__``:
```
        if sys.platform == "linux2":
```
When running under Python 3 on my RPi {{sys.platform}} returns "linux", not "linux2" (Python 2 does return "linux2"). Changing that line to:
```
        if sys.platform.startswith("linux"):
 ```
fixed the problem for me.

**Comment by ManuelMcLure** [comment]
I've created PR #78 to fix this.

**Comment by LazeMSS** [comment]
This is also fixed in current released version if im not mistaken @Cosik ?

**Comment by Cosik** [comment]
yes, correct
