### ISSUE TITLE
Feature request - can you add 'throttling' status?

### ISSUE THREAD

**Issue by HeneryH** [imrahil/OctoPrint-NavbarTemp#75]
Is it possible to add the current throttling status to the data collected?

When the CPU throttles, the command vcgencmd get_throttled outputs 0x20002 (the first 2 indicates the Pi has throttled at some point between the prior boot and now; the last 2 indicates the Pi is currently throttling the CPU frequency.

watch -n 1 vcgencmd get_throttled
watch -n 1 vcgencmd measure_temp

**Comment by LazeMSS** [comment]
This is a standard feature in Pi Support Plugin bundled with OctoPrint

**Comment by imrahil** [comment]
Unreleated
