### ISSUE TITLE
Problems with 64-bit OS on Raspberry

### ISSUE THREAD

**Issue by V0lk1s** [imrahil/OctoPrint-NavbarTemp#76]
I have found that the path for 'vcgencmd' is different on the 64-bit Raspberry OS. The only alternative I have found is /usr/bin/vcgencmd.

https://github.com/imrahil/OctoPrint-NavbarTemp/blob/0efd791a590b27b4ca281422be8395e6d1ff85a7/octoprint_navbartemp/libs/sbc.py#L103

**Comment by arekm** [comment]
Fixed by https://github.com/imrahil/OctoPrint-NavbarTemp/pull/93 in 0.15.
