### ISSUE TITLE
Feature request: select which hotends to display

### ISSUE THREAD

**Issue by fnordsh** [imrahil/OctoPrint-NavbarTemp#8]
It would be nice to be able to select which hotends' temperatures should be shown.

I have a Diamond Hotend which means that I have three extruders which share one nozzle and one heater. So I really only need to see one temperature, because they are always the same.
Other people might want to see only the temperature of the currently active extruder even if they don't share a heater.

So the config page might look like this:

```
[ ] Raspberry Pi internal temperature
[x] Bed
( ) All hotends
(o) The currently active hotend
( ) Selected hotends
    [x] Hotend 1
    [x] Hotend 2
    [ ] Hotend 3
```

**Comment by MennoLauwerens** [comment]
With the Diamond hotend and Repetier firmware I have 16 virtual extruders (color mixing), I have Octoprint setup for 1 extruder, and made custom commands to select the right one for manual operation.
It would be nice to have native support for this configuration.

**Comment by LazeMSS** [comment]
This is possible with my plugin: 
https://plugins.octoprint.org/plugins/toptemp/

Maybe give it a try?
