### ISSUE TITLE
Tool temp shows as 0°C when printer is turned off

### ISSUE THREAD

**Issue by timur-tabi** [imrahil/OctoPrint-NavbarTemp#80]
This is a very minor bug.

When the printer is turned on, NavbarTemp shows the SoC, Tool (extruder), and Bed temp just fine:

![Screenshot_20200727_110239](https://user-images.githubusercontent.com/1065860/88565069-b8a74e00-cff9-11ea-84b7-6bd802867ddb.png)

However, when the printer is turned off, the Bed temp is not shown (which is good), but the Tool temp is shown as 0°C (which is bad): 

![Screenshot_20200727_110836](https://user-images.githubusercontent.com/1065860/88565171-d674b300-cff9-11ea-8510-3d3189ca32c4.png)

It's inconsistent that NavbarTemp knows not to show the Bed temperature if the printer is off, but it also should not show the Tool temp if the printer is off.

**PLEASE CAREFULLY FILL EACH POINT**

**1. Hardware and operating system version:**

RPi 3B+
Linux octopi 4.14.34-v7+ #1110 SMP Mon Apr 16 15:18:51 BST 2018 armv7l GNU/Linux

**2. Octoprint version:**

OctoPrint version : 1.4.0
OctoPi version    : 0.15.1

**3. Plugin version:**

0.14

**4. Print screen of plugin configuration:**

![Screenshot_20200727_165948](https://user-images.githubusercontent.com/1065860/88596420-a4c81000-d02a-11ea-8205-8a3e02171482.png)

**5. Plugin full log file**

[octoprint.log](https://github.com/imrahil/OctoPrint-NavbarTemp/files/4984723/octoprint.log)

**Comment by LazeMSS** [comment]
Should be fixed in latest release

**Comment by Cosik** [comment]
@timur-tabi did you check it?

**Comment by timur-tabi** [comment]
I'm still on 0.14.  How do I test a pre-release version of your plugin?
