### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by adeebshihadeh** [imrahil/OctoPrint-NavbarTemp#9]
Not sure if I should file this as an OctoPrint or plugin bug. To prevent this in some cases, perhaps raspi temp should be disabled by default.
<img width="1679" alt="" src="https://cloud.githubusercontent.com/assets/8762862/9234331/154c6dd0-40ed-11e5-95df-508ed17edc6a.png">

**Comment by imrahil** [comment]
it's not a bug IMHO. there is just no space for such long texts on both sides...
