### ISSUE TITLE
[FEATURE REQUEST]  Add IP address or last network segment to NavBar :)

### ISSUE THREAD

**Issue by bolsoncerrado** [imrahil/OctoPrint-NavbarTemp#96]
I know it's a bit unrelated to "Temp" but a nice addition specially to troubleshoot printer farms ;)

To add either the full IP or the last IP .segment to the NavBar ;)

Prettypleeeeeease! :)

**Comment by imrahil** [comment]
C'mon! It's totally unreleated to "temp" feature. But I think it should be fairly easy to create a plugin for that (maybe it even exist already)
